name: colonia
description: Programa de gerenciamento de pescadores de Vitória do Xingu
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.8
  http: ^1.1.0
  desktop_multi_window: ^0.2.0
  file_picker: ^6.1.1
  open_filex: ^4.3.4
  brasil_fields: ^1.14.1
  get: ^4.6.5
  shared_preferences: ^2.2.2
  bitsdojo_window: ^0.1.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/fish.png